name: Generate Blog

on:
  push:
    paths:
      - 'articles/**/*.md'
      - 'scripts/generate.cjs'
      - 'static/**'
      - 'templates/**'
      - '.github/workflows/generate-blog.yml'
  workflow_dispatch:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: Run markdownlint
        run: markdownlint-cli2 "articles/**/*.md"

  generate-blog:
    runs-on: ubuntu-latest
    needs: markdown-lint

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Generate blog into build directory
        run: node scripts/generate.cjs

      - name: Prepare .gh-pages worktree
        run: |
          git fetch origin gh-pages
          git worktree add .gh-pages gh-pages

      - name: Clear .gh-pages contents
        run: rm -rf .gh-pages/*

      - name: Copy generated files to .gh-pages
        run: cp -r build/* .gh-pages/

      - name: Add .nojekyll
        run: touch .gh-pages/.nojekyll

      - name: Commit and push to gh-pages
        run: |
          cd .gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: auto-generate blog pages" || echo "No changes to commit"
          git push origin gh-pages --force
